package api

// ssh request types
const (
	SSHRequestMytoken                 = "MT"
	SSHRequestAccessToken             = "AT"
	SSHRequestTokenInfoIntrospect     = "introspect"
	SSHRequestTokenInfoHistory        = "history"
	SSHRequestTokenInfoSubtokens      = "list-subtokens"
	SSHRequestTokenInfoListMytokens   = "list-all-mytokens"
	SSHRequestTokenInfoNotifications  = "tokeninfo-notifications"
	SSHRequestRevoke                  = "revoke"
	SSHRequestAddTag                  = "add-tag"
	SSHRequestRemoveTag               = "remove-tag"
	SSHRequestEmailGet                = "email-get"
	SSHRequestEmailSet                = "email-set"
	SSHRequestTagsList                = "tags-list"
	SSHRequestTagCreate               = "tag-create"
	SSHRequestTagUpdate               = "tag-update"
	SSHRequestTagDelete               = "tag-delete"
	SSHRequestNotifications           = "notifications"
	SSHRequestNotificationCreate      = "notification-create"
	SSHRequestNotificationAddToken    = "notification-add-token"
	SSHRequestNotificationRemoveToken = "notification-remove-token"
	SSHRequestNotificationUpdate      = "notification-update"
	SSHRequestNotificationDelete      = "notification-delete"
	SSHRequestCalendars               = "calendars"
	SSHRequestCalendarCreate          = "calendar-create"
	SSHRequestCalendarGet             = "calendar-get"
	SSHRequestCalendarUpdate          = "calendar-update"
	SSHRequestCalendarDelete          = "calendar-delete"
	SSHRequestCalendarAddMytoken      = "calendar-add-mytoken"
	SSHRequestCalendarRemoveMytoken   = "calendar-remove-mytoken"
	SSHRequestCalendarAddTag          = "calendar-add-tag"
	SSHRequestCalendarRemoveTag       = "calendar-remove-tag"
)
